
signUp:
    path: /signup
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\accessController::signUp


app_login:
    path: /login
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\accessController::login

home:
    path: /home
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\HomeController::loadHomePage

api_fyp_function:
    path: /api/fyp-function
    controller: App\Controller\HomeController::fyp_function

productPage:
    path: /product/{productId}
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\HomeController::loadProductPage

userPage:
    path: /user/{username}
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\HomeController::loadUserPage

crateProduct:
    path: /createproduct
    controller: App\Controller\HomeController::createProduct

app_logout:
    path: /access/logout
    controller: App\Controller\accessController::logout

payment:
    path: /payment
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\PaymentController::loadPaymentPage