
signUp:
    path: /signup
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\accessController::signUp


app_login:
    path: /login
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\accessController::login

home:
    path: /home
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\HomeController::loadHomePage

api_fyp_function:
    path: /api/fyp-function/{qta}-{position}
    controller: App\Controller\HomeController::fyp_function

transactions_history:
    path: /transactions_history
    controller: App\Controller\HomeController::loadTransactionsHistoryPage


productPage:
    path: /product/{productId}
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\HomeController::loadProductPage

userPage:
    path: /user/{username}
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\HomeController::loadUserPage

crateProduct:
    path: /createproduct
    controller: App\Controller\HomeController::createProduct

edit_product:
    path: editproduct/{id}
    controller: App\Controller\HomeController::editProduct

app_logout:
    path: /access/logout
    controller: App\Controller\accessController::logout

get_product_by_popular:
    path: /api/getProductByPopular/{qta}-{position}
    controller: App\Controller\HomeController::getProductByPopular

delete_product:
    path: deleteproduct/{id}
    controller: App\Controller\HomeController::deleteProduct
    
load_popular_products_page:
    path: /populars
    controller: App\Controller\HomeController::loadPopularProductsPage

payment:
    path: /payment
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\PaymentController::loadPaymentPage

