
access:
    path: /access
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\accessController::loadAccessPage

signUp:
    path: /access/signup
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\accessController::signUp


app_login:
    path: /access/login
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\accessController::login

home:
    path: /home
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\HomeController::loadHomePage

productPage:
    path: /product/{productId}
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\HomeController::loadProductPage

userPage:
    path: /user/{username}
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\HomeController::loadUserPage

editProduct:
    path: /editproduct/{id}
    controller: App\Controller\HomeController::loadProductEditPage

app_logout:
    path: /access/logout
    controller: App\Controller\accessController::logout