
access:
    path: /access
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\accessController::loadAccessPage

signUp:
    path: /access/signup


app_login:
    path: /access/login
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\accessController::login

home:
    path: /home
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\HomeController::loadHomePage

app_logout:
    path: /access/logout
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\accessController::logout